from __future__ import annotations

from typing import Any


def _num(value: Any, default: float = 0) -> float:
    """
    Convert a value to a number safely.
    """
    if value is None or value == "":
        return default

    try:
        return float(value)
    except (TypeError, ValueError):
        return default


def _sap_number(value: Any, width: int = 4) -> str:
    """
    Convert operation/component numbers into SAP-style zero-padded strings.

    Examples:
        10 -> "0010"
        20 -> "0020"
        "30" -> "0030"
        "0010" -> "0010"
    """
    if value is None or value == "":
        return ""

    try:
        return str(int(value)).zfill(width)
    except (TypeError, ValueError):
        return str(value)


def _as_list(value: Any) -> list[dict[str, Any]]:
    """
    Safely convert a JSON array into a list of dictionaries.
    """
    if not isinstance(value, list):
        return []

    return [
        item
        for item in value
        if isinstance(item, dict)
    ]


def build_sap_payload(data: dict[str, Any]) -> dict[str, Any]:
    """
    Convert the JSON generated by buildOarcJson()
    into the SAP-style structure used by the SAP service.

    Input:
        Route-card/OARC JSON

    Output:
        {
            "WaHeader": {...},
            "ItComponents": {
                "item": [...]
            },
            "ItOperation": {
                "item": [...]
            },
            "ItOrdslno": {
                "item": [...]
            }
        }
    """

    operations = _as_list(data.get("Operations"))
    raw_materials = _as_list(data.get("Raw Materials"))

    # ---------------------------------------------------------
    # Header
    # ---------------------------------------------------------

    header = {
        "Aufnr": data.get("Prod Order No") or "",
        "Bukrs": None,
        "Werks": data.get("Plant") or "",
        "Matnr": data.get("Part No") or "",
        "Maktx": data.get("Part Desc") or "",
        "Gamng": _num(data.get("Required Qty"), 1),
        "Gmein": None,
        "Plnty": None,
        "Plnnr": None,
        "Plnal": None,
    }

    # ---------------------------------------------------------
    # Components / Raw Materials
    # ---------------------------------------------------------

    components = []

    for material in raw_materials:
        components.append(
            {
                "Posnr": _sap_number(material.get("Sl.No")),
                "Matnr": material.get("Child Part No") or "",
                "Romen": None,
                "Meins": material.get("UoM") or "NO",
                "Bdmng": _num(material.get("Total Qty"), 0),
                "Maktx": material.get("Description") or "",
            }
        )

    # ---------------------------------------------------------
    # Operations
    # ---------------------------------------------------------

    sap_operations = []

    for operation in operations:
        work_center = (
            operation.get("work_center_code")
            or operation.get("Work Center")
            or operation.get("Wc/Plant")
            or ""
        )

        sap_operations.append(
            {
                "Vornr": _sap_number(operation.get("Oprn No")),
                "Ltxa1": operation.get("Operation") or "",
                "Arbpl": work_center,
                "WcWerks": operation.get("Plant Number") or "",
                "Setuptime": _num(operation.get("Setup Time"), 0),
                "Setupuom": None,
                "Perpiecetime": _num(operation.get("Per Pc Time"), 0),
                "Perpieceuom": None,
                "JmpQty": _num(operation.get("Jmp Qty"), 0),
                "TotQty": _num(operation.get("Tot Qty"), 0),
                "AlTime": _num(operation.get("Allowed Time"), 0),
                "ActTime": None,
                "Rueck": operation.get("Confirm No") or "",
                "CompMatnr": None,
                "NoParts": None,
            }
        )

    # ---------------------------------------------------------
    # Serial numbers
    #
    # Route-card JSON currently does not provide serial numbers,
    # so we return an empty SAP table.
    # ---------------------------------------------------------

    serial_numbers: list[dict[str, Any]] = []

    # ---------------------------------------------------------
    # Final SAP structure
    # ---------------------------------------------------------

    return {
        "WaHeader": header,
        "ItComponents": {
            "item": components
        },
        "ItOperation": {
            "item": sap_operations
        },
        "ItOrdslno": {
            "item": serial_numbers
        },
    }